Repository mattermost/mattermost-test-management, pull requests merged in 2022-11, with the labels that each got.

#5 test(mark as unread): latest post should appear unread after marking the channel as unread in LHS via menu option or shortcut key
  data/test-cases/channels/mark-as-unread/mark-channel-unread1.md
  data/test-cases/channels/mark-as-unread/mark-channel-unread2.md
Labels: 3: Reviews Complete

#6 chore(docs): add template for pull requests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3: Reviews Complete

#14 test(MM-T4886): Update step 2 for existing test MM-T4886.md
  data/test-cases/mobile-v2/smoke-test/MM-T4886.md
Labels: 3: Reviews Complete

#17 chore: add deno.lock and upgrade stdlib to 0.165.0
  deno.lock
  src/deps.ts
  www/deno.lock
  www/import_map.json
Labels: 2: Dev Review

#8 add actions to run deno validation tasks for PULL REQUESTS
  .github/workflows/deno.yml
  deno.lock
Labels: Awaiting Submitter Action

#19 test(insight, ad-ldap and user groups): added test cases
  data/test-cases/suite/activity-and-insights/insights/MM-Test-Case-1.md
  data/test-cases/suite/ad-ldap/MM-test-case-1.md
  data/test-cases/suite/enterprise/user-groups/MM-Test-Case-1.md
  data/test-cases/suite/enterprise/user-groups/MM-Test-Case-2.md
  data/test-cases/suite/enterprise/user-groups/MM-Test-Case-3.md
Labels: 3: Reviews Complete

#23 test(Sidebar) : Should not crash the app, when the rhs is opened and user goes to and back from system console
  data/test-cases/channels/sidebar/MM-X1.md
  data/test-cases/channels/sidebar/MM-X2.md
  data/test-cases/channels/sidebar/MM-X3.md
  data/test-cases/channels/sidebar/MM-X4.md
  data/test-cases/channels/sidebar/MM-X5.md
  data/test-cases/channels/sidebar/MM-X6.md
  data/test-cases/channels/sidebar/MM-X7.md
  data/test-cases/channels/sidebar/MM-X8.md
Labels: 3: Reviews Complete
