Repository mattermost/mattermost-test-management, pull requests merged in 2023-01, with the labels that each got.

#42 test(MM-T4676): Updating server error step 3.
  data/test-cases/mobile-v2/server-login/MM-T4676.md
Labels: 3: Reviews Complete

#45 fix: Update test data and test cases for markdown latex and list
  data/test-cases/mobile-v2/messaging/MM-T4897.md
  data/test-cases/mobile-v2/messaging/MM-T4900.md
Labels: 3: Reviews Complete

#46 test(MM-T4871): Small changes to clarify steps
  data/test-cases/cloud/signup-trial-and-upgrade/MM-T4871.md
Labels: 3: Reviews Complete

#49 est(MM-T4870): Update onboarding task list to reflect current design
  data/test-cases/cloud/signup-trial-and-upgrade/MM-T4870.md
Labels: 3: Reviews Complete

#47 test(MM-T5141): Update to reflect new functionality
  data/test-cases/channels/channels/MM-T5141.md
Labels: 3: Reviews Complete

#50 feat(true-up): Test cases for true-up: Support for customers with no connectivity
  data/test-by-folder.json
  data/test-cases/self-hosted/true-up-support/test-1.md
  data/test-cases/self-hosted/true-up-support/test-2.md
  data/test-cases/self-hosted/true-up-support/test-3.md
Labels: 1: PM Review, QA Review Done

#51 test(MM-T5366): Updating test name to follow folder naming convention and setting active status
  data/test-cases/channels/global-drafts/MM-T4409.md
  data/test-cases/channels/global-drafts/MM-T4410.md
  data/test-cases/channels/global-drafts/MM-T4411.md
  data/test-cases/channels/global-drafts/MM-T4412.md
  data/test-cases/channels/global-drafts/MM-T4413.md
  data/test-cases/channels/global-drafts/MM-T4414.md
  data/test-cases/channels/global-drafts/MM-T5366.md
Labels: 3: Reviews Complete

#52 test(MM-T5178): Updated regular user onboarding checklist
  data/asset/Regular_user_onboarding_checklist.png
  data/test-cases/cloud/signup-trial-and-upgrade/MM-T5178.md
Labels: 3: Reviews Complete

#58 test(MM-43924): Should match title and custom description in root html
  data/test-cases/suite/system-console/MM-Tnnn.md
Labels: 3: Reviews Complete

#57 test(MM-T5360): Mobile V2: Invite - Copy and share invite link
  data/asset/ShareSheet_Android.png
  data/asset/ShareSheet_iOS.png
  data/asset/plus_sign_menu.jpeg
  data/test-cases/mobile-v2/invite-people/MM-T5360.md
  data/test-cases/mobile-v2/invite-people/MM-T5362.md
Labels: 2: QA Review

#54 test(Work Templates): Create a work template
  data/asset/work_template_modal.png
  data/test-cases/suite/Work-Templates/Create-a-work-template.md
Labels: 2: QA Review
