Repository mattermost/mattermost-test-management, pull requests merged in 2023-04, with the labels that each got.

#89 test(MM-T1703): Update steps with new UI including More Channels to Browse Channels
  data/test-cases/channels/archived-channels/MM-T1703.md
Labels: 3: Reviews Complete

#88 test(MM-T1697): Update steps with new UI including `More Channels` to `Browse Channels`
  data/test-cases/channels/archived-channels/MM-T1697.md
Labels: 3: Reviews Complete

#77 Added Verify Forgot Password link test cases
  data/test-cases/suite/sign-in-authentication/MM-Test-Case-1.md
Labels: 3: Reviews Complete

#83 test: discard message edits after cancelling
  data/test-cases/channels/messaging/cancel-message-editing.md
Labels: 2: QA Review, Contributor

#86 Feat: Cloud Free Deprecation test case
  data/test-by-folder.json
  data/test-cases/cloud/automated-tests/system-console/billing-history-/MM-T4157.md
  data/test-cases/cloud/cloud-free-deprecation/test-1.md
  data/test-cases/cloud/cloud-free-deprecation/test-2.md
  data/test-cases/cloud/cloud-trial/MM-T4246.md
  data/test-cases/cloud/signup-trial-and-upgrade/MM-T4892.md
Labels: 1: PM Review, 2: Dev Review

#93 feat: add email to Auth header when fetching components
  src/util/jira.ts
Labels: 3: Reviews Complete

#90 Feat: Cloud Trial Lifecycle
  data/test-by-folder.json
  data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-1.md
  data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-2.md
Labels: 1: PM Review, 2: Dev Review
